### ISSUE TITLE
Utilities issue

### ISSUE THREAD

**Issue by GraceAnyelwisye** [rwb27/openflexure_microscope#39]
1.What is the use of utilities? Why in almost all objects/parts you have included utilities? What is the relationship with the design? In some other parts, when I comment out utilities there is no significant change that I can observe. 

2. What does trylinder, shaft and delta mean in utilities?

**Comment by rwb27** [comment]
Hello
``utilities.scad`` contains a lot of useful functions, which are used in pretty much all the other files.  It doesn't create anything on its own, but it defines things like for example ``reflect(axis)`` which duplicates an object by reflecting it along a given axis.  It's like ``mirror`` only it keeps the original object.  While it's possible that some of the files don't actually need it, I tend to leave it in just in case.

"trylinder" generally refers to a shape that is somewhere between a triangle and a cylinder.  It's used in the lens grippers in the optics module (it is a shape that deforms to be a cylinder).

"shaft" is often used in connection to holes for screws/nuts - if "shaft=true" is specified, it will make a long hole for the shaft (threaded part) of the screw rather than just a hexagonal hole for the nut.

"delta" is used in the ``repeat`` module, and it sets the distance between the copies of the objects (it's a 3-element vector).
